"use client";

import {
  Smartphone,
  Monitor,
  Layout,
  Zap,
  Eye,
  Globe,
  Palette,
  Code,
  Shield,
  Bell,
  Star,
  Heart,
  Info,
  AlertTriangle,
  CheckCircle,
  Clock,
  MapPin,
  Users,
  Settings,
  TrendingUp,
  BarChart3,
  PieChart,
  Activity,
  Cpu,
  Database,
  Wifi,
  Camera,
  Image,
  MessageCircle,
  Mail,
  Search,
  Filter,
  Layers,
  Grid3X3,
  List,
  Hash,
  Tag,
  Bookmark,
  Award,
  Target,
  Compass,
  Navigation,
  Terminal,
  Briefcase,
  ShoppingCart,
  Music,
  Film,
  Mic,
  type LucideProps,
} from "lucide-react";
import { type FC } from "react";

const iconMap: Record<string, FC<LucideProps>> = {
  smartphone: Smartphone,
  monitor: Monitor,
  layout: Layout,
  zap: Zap,
  eye: Eye,
  globe: Globe,
  palette: Palette,
  code: Code,
  shield: Shield,
  bell: Bell,
  star: Star,
  heart: Heart,
  info: Info,
  alertTriangle: AlertTriangle,
  checkCircle: CheckCircle,
  clock: Clock,
  mapPin: MapPin,
  users: Users,
  settings: Settings,
  trending: TrendingUp,
  barChart: BarChart3,
  pieChart: PieChart,
  activity: Activity,
  cpu: Cpu,
  database: Database,
  wifi: Wifi,
  camera: Camera,
  image: Image,
  messageCircle: MessageCircle,
  mail: Mail,
  search: Search,
  filter: Filter,
  layers: Layers,
  grid: Grid3X3,
  list: List,
  hash: Hash,
  tag: Tag,
  bookmark: Bookmark,
  award: Award,
  target: Target,
  compass: Compass,
  navigation: Navigation,
  terminal: Terminal,
  briefcase: Briefcase,
  shoppingCart: ShoppingCart,
  music: Music,
  film: Film,
  mic: Mic,
};

export function DynamicIcon({
  name,
  ...props
}: { name: string } & LucideProps) {
  const Icon = iconMap[name] || Zap;
  return <Icon {...props} />;
}
